### ISSUE TITLE
Lost auto-completion in shell

### ISSUE THREAD

**Issue by guozhaohui** [justmao945/vim-clang#25] opened 2015-02-16 04:46 UTC
After installed clang.vim, when use :sh　switch to shell in vim. the command 
auto-completion of shell was lost. the prompt of shell is only $, no any path info.

The version info. of my VIM is as followings.
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
patch: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@

**Comment by justmao945** [comment] 2015-02-16 04:52
I can't understand the problem, can you take some screenshots about this problem?
I try :sh in my vim, it works well.

**Comment by guozhaohui** [comment] 2015-02-16 05:24
I have found the answer.
in clang.vim ln.92 
 let g:clang_sh_exec = 'sh'

sh command is different with bash on my PC, which does not support command auto-completion.

**Comment by justmao945** [comment] 2015-02-16 05:48
`sh` will only be set when calling clang command, then stored after called automatically.
I am not sure why this configure has effect on `:sh`.

**Comment by justmao945** [comment] 2015-02-16 06:01
Thank you @guozhaohui , I found a bug that won't restore global vars including `shell` when call the init function. Now fixed in master, please update and see whether the problem is still exist or not.

**Comment by guozhaohui** [comment] 2015-02-16 09:09
The newest version seems OK. Not only the shell command auto-completion, but also the Pmenu/PmenuSel　color config  work correctly now. 

Thank you!

**Comment by justmao945** [comment] 2015-02-16 09:45
OK. :laughing:

**Closed by justmao945** 2015-02-16 09:45 UTC
